#!/usr/bin/env python3
"""
bot_groq.py
Groq-powered Telegram PDF Summarizer + MCQ generator.
Features:
 - Chunked summarization for large PDFs
 - Concurrent LLM calls (fast)
 - Robust JSON extraction for MCQs
 - Persistent rate-limiting & caching (Deta Base)
 - GitHub Pages publishing (create/update with SHA)
 - Monetag ad injection
 - Deployable on Deta Space (free)
"""

from __future__ import annotations
import os, io, json, time, base64, hashlib, logging, textwrap
from datetime import datetime, timedelta
from typing import List, Dict, Any, Optional
import asyncio
import requests
import pdfplumber
from jinja2 import Template
from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes
from deta import Deta

# ------------------------------
# CONFIG: set as environment variables
# ------------------------------
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
GITHUB_USERNAME = os.getenv("GITHUB_USERNAME")            # username
GITHUB_REPO = os.getenv("GITHUB_REPO", "pdfstudy-pages") # repo name
GITHUB_PAT = os.getenv("GITHUB_PAT")
GITHUB_BRANCH = os.getenv("GITHUB_BRANCH", "main")       # branch to push to
PAGE_BASE = f"https://{GITHUB_USERNAME}.github.io/{GITHUB_REPO}"

# Groq (OpenAI-compatible) config
GROQ_API_KEY = os.getenv("GROQ_API_KEY")                  # your Groq API key
GROQ_MODEL = os.getenv("GROQ_MODEL", "groq/llama3-70b-8192")
GROQ_BASE = os.getenv("GROQ_BASE_URL", "https://api.groq.com/openai/v1")  # OpenAI-compatible base path

# Monetag ad snippet (JS). Put your Monetag snippet here or in env var.
MONETAG_CODE = os.getenv("MONETAG_CODE", "<!-- monetag placeholder -->")

# Deta
DETA_PROJECT_KEY = os.getenv("DETA_PROJECT_KEY")         # required for Deta
# Limits & tuning
PAGE_LIMIT = int(os.getenv("PAGE_LIMIT", "50"))          # how many PDF pages to read max (tune)
CHUNK_CHARS = int(os.getenv("CHUNK_CHARS", "3500"))      # chunk size (characters)
MAX_MCQS = int(os.getenv("MAX_MCQS", "5"))

# Rate-limiting (per user per hour)
RATE_LIMIT_PER_HOUR = int(os.getenv("RATE_LIMIT_PER_HOUR", "20"))

# Timeouts
GROQ_TIMEOUT = int(os.getenv("GROQ_TIMEOUT", "30"))      # seconds for Groq calls
GITHUB_TIMEOUT = int(os.getenv("GITHUB_TIMEOUT", "20"))

# Logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s: %(message)s")
logger = logging.getLogger("bot_groq")

# ------------------------------
# Validate config quickly
# ------------------------------
if not TELEGRAM_BOT_TOKEN:
    logger.error("Missing TELEGRAM_BOT_TOKEN env var. Aborting.")
if not GROQ_API_KEY:
    logger.warning("GROQ_API_KEY not set — Groq calls will fail until provided.")
if not (GITHUB_USERNAME and GITHUB_REPO and GITHUB_PAT):
    logger.warning("GitHub config missing — publishing will fail until set.")

# ------------------------------
# Initialize Deta (persistent stores)
# ------------------------------
if DETA_PROJECT_KEY:
    deta = Deta(DETA_PROJECT_KEY)
else:
    # If DETA_PROJECT_KEY not provided, try unauthenticated (will fail for Base)
    deta = None

# Deta Bases
summaries_db = deta.Base("summaries") if deta else None      # cache: key = sha256(file)
rate_db = deta.Base("rate_limits") if deta else None        # rate limits: key = user_YYYYMMDDHH
meta_db = deta.Base("meta") if deta else None              # optional (not heavily used)

# ------------------------------
# HTML templates (Jinja2)
# ------------------------------
SUMMARY_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ title|e }}</title>
<meta name="description" content="{{ snippet|e }}">
<style>
body{font-family:system-ui,Arial,Helvetica,sans-serif;max-width:900px;margin:0 auto;padding:18px;line-height:1.6}
header{background:linear-gradient(135deg,#667eea,#764ba2);color:#fff;padding:20px;border-radius:8px;margin-bottom:16px}
.container{background:#fff;padding:18px;border-radius:8px;box-shadow:0 6px 18px rgba(0,0,0,0.06)}
.ad{margin:18px 0;text-align:center}
.summary{white-space:pre-wrap;background:#f8f9fa;padding:12px;border-radius:6px}
.keypoints{margin-top:12px}
.cta{display:inline-block;margin-top:16px;padding:10px 14px;background:#28a745;color:#fff;border-radius:6px;text-decoration:none}
footer{color:#666;font-size:0.9rem;margin-top:20px;text-align:center}
</style>
</head>
<body>
<header><h1>📚 {{ title|e }}</h1><p style="opacity:0.9;margin-top:6px">Generated by PDF Study Bot</p></header>
<div class="container">
  <div class="ad">{{ monetag_code | safe }}</div>
  <section class="summary"><h2>Summary</h2><div>{{ summary_html | safe }}</div></section>
  <section class="keypoints"><h3>Key Points</h3><ul>{% for p in key_points %}<li>{{ p|e }}</li>{% endfor %}</ul></section>
  <a class="cta" href="{{ quiz_url }}">📝 Take Quiz (MCQs)</a>
  <div class="ad" style="margin-top:20px">{{ monetag_code | safe }}</div>
  <footer>Share with classmates • Generated on {{ ts }}</footer>
</div>
</body>
</html>
"""

QUIZ_TEMPLATE = """<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Quiz - {{ title|e }}</title>
<style>
body{font-family:system-ui,Arial,Helvetica,sans-serif;max-width:900px;margin:0 auto;padding:18px}
.header{background:linear-gradient(135deg,#ff7a7a,#ffbe7a);color:#fff;padding:18px;border-radius:8px}
.container{background:#fff;padding:18px;border-radius:8px;box-shadow:0 6px 18px rgba(0,0,0,0.06);margin-top:12px}
.question{margin:14px 0;padding:12px;border-radius:6px;background:#f7f9fc}
.option{margin:6px 0;padding:10px;background:#fff;border-radius:6px;cursor:pointer}
.btn{padding:10px 14px;border-radius:6px;background:#0077ff;color:#fff;border:none;cursor:pointer}
.ad{margin:18px 0;text-align:center}
.expl{margin-top:8px;background:#eef;padding:10px;border-radius:6px}
</style>
</head><body>
<div class="header"><h1>📝 Quiz: {{ title|e }}</h1><p style="opacity:.9">Medium → Hard MCQs</p></div>
<div class="ad">{{ monetag_code | safe }}</div>
<div class="container">
<form id="quizForm">
{% for q in mcqs %}
  <div class="question" id="q{{ loop.index0 }}">
    <strong>Q{{ loop.index }}. {{ q.question }}</strong>
    <div style="margin-top:8px">
      {% for opt in q.options %}
      <label class="option"><input type="radio" name="q{{ loop.index0 }}" value="{{ opt|e }}"> {{ opt|e }}</label>
      {% endfor %}
    </div>
    <div class="expl" id="exp{{ loop.index0 }}" style="display:none"><strong>Explanation:</strong><div>{{ q.explanation }}</div></div>
  </div>
{% endfor %}
</form>
<div style="margin-top:14px;text-align:center">
<button class="btn" onclick="grade()">Submit</button>
<button class="btn" onclick="retry()" style="background:#28a745">Retry</button>
</div>
<div id="result" style="margin-top:18px"></div>
<div class="ad" style="margin-top:18px">{{ monetag_code | safe }}</div>
</div>

<script>
const answers = {{ answers_json | safe }};
function grade(){
  let total = answers.length, score = 0;
  for(let i=0;i<total;i++){
    const sel = document.querySelector('input[name="q'+i+'"]:checked');
    if(sel && sel.value === answers[i]) score++;
    document.getElementById('exp'+i).style.display = 'block';
  }
  const perc = Math.round((score/total)*100);
  let msg = `<h3>Your Score: ${score}/${total} (${perc}%)</h3>`;
  if(perc>=70) msg += '<p>🔥 Excellent</p>';
  else if(perc>=50) msg += '<p>🙂 Good</p>';
  else msg += '<p>💡 Keep practicing</p>';
  document.getElementById('result').innerHTML = msg;
}
function retry(){ window.location.reload(); }
</script>
</body></html>
"""

# ------------------------------
# Utility helpers
# ------------------------------
def sha256_bytes(b: bytes) -> str:
    import hashlib
    return hashlib.sha256(b).hexdigest()

def split_text_into_chunks(text: str, chunk_chars: int = CHUNK_CHARS) -> List[str]:
    """Split by paragraphs + char window to keep chunks coherent."""
    paras = [p.strip() for p in text.split("\n\n") if p.strip()]
    chunks = []
    cur = ""
    for p in paras:
        if len(cur) + len(p) + 2 <= chunk_chars:
            cur += ("\n\n" if cur else "") + p
        else:
            if cur:
                chunks.append(cur)
            # If single paragraph huge, break it
            if len(p) > chunk_chars:
                for i in range(0, len(p), chunk_chars):
                    chunks.append(p[i:i+chunk_chars])
                cur = ""
            else:
                cur = p
    if cur:
        chunks.append(cur)
    return chunks

def extract_text_from_pdf_bytes(pdf_bytes: bytes, page_limit: int = PAGE_LIMIT) -> str:
    """Extract text from PDF using pdfplumber; fallbacks minimal."""
    text_parts = []
    try:
        with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
            total = min(len(pdf.pages), page_limit)
            for i, page in enumerate(pdf.pages[:page_limit]):
                ptext = page.extract_text() or ""
                text_parts.append(ptext)
    except Exception as e:
        logger.exception("PDF parsing error: %s", e)
    return "\n\n".join([p for p in text_parts if p]).strip()

# ------------------------------
# Groq call helpers (OpenAI-style chat completions)
# ------------------------------
def call_groq_chat_sync(messages: List[Dict[str,str]], model: str = GROQ_MODEL, timeout: int = GROQ_TIMEOUT) -> Dict[str, Any]:
    """
    Calls Groq's OpenAI-compatible chat completions endpoint synchronously.
    Use asyncio.to_thread to call this without blocking the event loop.
    """
    if not GROQ_API_KEY:
        raise RuntimeError("Missing GROQ_API_KEY env var")
    url = f"{GROQ_BASE}/chat/completions"
    headers = {"Authorization": f"Bearer {GROQ_API_KEY}", "Content-Type": "application/json"}
    payload = {"model": model, "messages": messages, "temperature": 0.0, "max_tokens": 1200}
    resp = requests.post(url, headers=headers, json=payload, timeout=timeout)
    resp.raise_for_status()
    return resp.json()

def parse_json_from_text(text: str) -> Optional[Any]:
    """Find the first JSON object/array in text and parse it robustly."""
    text = text.strip()
    # remove leading/trailing code fences
    for fence in ["```json", "```"]:
        if fence in text:
            parts = text.split(fence)
            # pick the section that looks like JSON
            for part in parts[1:]:
                cand = part.split("```")[0]
                cand = cand.strip()
                try:
                    return json.loads(cand)
                except:
                    continue
    # fallback: find first { ... } or [ ... ]
    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        cand = text[start:end+1]
        try:
            return json.loads(cand)
        except:
            pass
    start = text.find("[")
    end = text.rfind("]")
    if start != -1 and end != -1 and end > start:
        cand = text[start:end+1]
        try:
            return json.loads(cand)
        except:
            pass
    return None

# ------------------------------
# Structured generation: chunk summarization -> combine -> MCQs
# ------------------------------
async def generate_summary_and_mcqs(text: str) -> Dict[str, Any]:
    """
    High-level orchestration:
     1. Split to chunks
     2. Summarize each chunk (parallel)
     3. Combine chunk summaries into final summary + key points
     4. Ask LLM to generate MCQs based on final summary (structured JSON)
    """
    # 1) chunk
    chunks = split_text_into_chunks(text, CHUNK_CHARS)
    logger.info("Text split into %d chunks (chars chunk=%d)", len(chunks), CHUNK_CHARS)

    # 2) summarize each chunk in parallel (use asyncio.to_thread for blocking requests)
    async def summarize_chunk(idx:int, chunk:str):
        system = {"role":"system","content":"You are a helpful summarization assistant. Produce a concise ~120-200 word summary of the content."}
        user = {"role":"user","content": f"Summarize this content in ~120-200 words, with clear headings if appropriate. Content:\n\n{chunk}"}
        try:
            resp = await asyncio.to_thread(call_groq_chat_sync, [system, user])
            # extract text from resp
            text_out = ""
            try:
                # OpenAI-style: resp['choices'][0]['message']['content']
                text_out = resp.get("choices", [{}])[0].get("message", {}).get("content", "")
            except Exception:
                text_out = str(resp)
            return {"idx":idx, "summary": text_out}
        except Exception as e:
            logger.exception("Chunk summary failed idx=%d: %s", idx, e)
            return {"idx":idx, "summary": ""}

    tasks = [summarize_chunk(i,c) for i,c in enumerate(chunks)]
    chunk_summaries = await asyncio.gather(*tasks)

    # 3) combine chunk summaries
    combined = "\n\n".join([cs["summary"] for cs in sorted(chunk_summaries, key=lambda x:x["idx"]) if cs["summary"]])
    # If combined is too long, chunk it again and summarize to a final summary
    combine_messages = [
        {"role":"system","content":"You are a senior academic editor. Combine the following chunk summaries into one coherent final summary (200-350 words). Also output 6-8 key bullet points."},
        {"role":"user","content": f"CHUNK_SUMMARIES:\n\n{combined[:12000]}"}  # trim safety
    ]
    try:
        combined_resp = await asyncio.to_thread(call_groq_chat_sync, combine_messages)
        final_text = combined_resp.get("choices", [{}])[0].get("message", {}).get("content", "")
    except Exception as e:
        logger.exception("Combine summary failed: %s", e)
        # fallback: use first N chunk summaries joined
        final_text = "\n\n".join([cs["summary"] for cs in chunk_summaries[:3]])

    # Attempt to extract a plain textual summary and keypoints
    # Ask Groq to return JSON with summary & key_points & mcqs
    structured_prompt = textwrap.dedent(f"""
    Return JSON only in this exact format (no extra text):
    {{
      "summary": "200-350 word summary string",
      "key_points": ["point1","point2", "..."],
      "mcqs": [
        {{
          "question": "...",
          "options": ["opt1","opt2","opt3","opt4"],
          "answer": "the exact correct option text",
          "explanation": "brief explanation why correct and why others are wrong"
        }}
      ]
    }}
    Use the following FINAL_CONTENT for context:
    {final_text[:9000]}
    Please produce {MAX_MCQS} MCQs with medium-to-hard difficulty, tricky distractors, and ensure answer equals one of the options.
    """)

    try:
        struct_resp = await asyncio.to_thread(call_groq_chat_sync, [{"role":"user","content":structured_prompt}])
        raw = struct_resp.get("choices", [{}])[0].get("message", {}).get("content", "")
    except Exception as e:
        logger.exception("Structured generation failed: %s", e)
        raw = ""

    parsed = parse_json_from_text(raw) if raw else None
    if not parsed:
        # fallback: ask simpler JSON-only prompt once more
        try:
            simpler = [
                {"role":"user","content": "Produce JSON ONLY with 'summary','key_points' (list) and 'mcqs' (list of objects with question/options/answer/explanation). Use the following content:\n\n" + final_text[:6000]}
            ]
            retry_resp = await asyncio.to_thread(call_groq_chat_sync, simpler)
            raw2 = retry_resp.get("choices", [{}])[0].get("message", {}).get("content", "")
            parsed = parse_json_from_text(raw2)
        except Exception:
            parsed = None

    # if still not parsed, build fallback structure
    if not parsed:
        # simple extraction heuristics
        summary_snip = (final_text[:1800] + "...") if final_text else "Summary unavailable."
        key_points = []
        # try to extract lines that look like bullets
        for line in (final_text.splitlines()):
            s = line.strip()
            if len(s) > 30 and len(key_points) < 6:
                key_points.append(s[:120])
        mcqs = []
        for i in range(MAX_MCQS):
            mcqs.append({
                "question": f"Fallback question {i+1} about the PDF content.",
                "options": ["Option A","Option B","Option C","Option D"],
                "answer": "Option A",
                "explanation": "Fallback explanation."
            })
        parsed = {"summary": summary_snip, "key_points": key_points or ["Key points not available"], "mcqs": mcqs}

    # Ensure options and answers are consistent and trim lengths
    for q in parsed.get("mcqs", []):
        if "options" not in q or not isinstance(q["options"], list) or len(q["options"]) < 2:
            q["options"] = ["Option A","Option B","Option C","Option D"]
        # Make sure answer matches one option; if answer is index, map it
        ans = q.get("answer","")
        if isinstance(ans, int):
            idx = int(ans)
            if 0 <= idx < len(q["options"]):
                q["answer"] = q["options"][idx]
            else:
                q["answer"] = q["options"][0]
        elif ans not in q["options"]:
            # try uppercase letters
            if str(ans).strip().upper() in ["A","B","C","D"]:
                map_idx = {"A":0,"B":1,"C":2,"D":3}[str(ans).strip().upper()]
                if map_idx < len(q["options"]):
                    q["answer"] = q["options"][map_idx]
                else:
                    q["answer"] = q["options"][0]
            else:
                q["answer"] = q["options"][0]

    return parsed

# ------------------------------
# GitHub Contents API helpers (create/update with SHA)
# ------------------------------
def github_api_put_file(path: str, content_str: str, commit_msg: str) -> bool:
    """
    Create or update file in the target repo branch.
    path: "summaries/abcd.html"
    """
    if not (GITHUB_USERNAME and GITHUB_REPO and GITHUB_PAT):
        logger.error("GitHub not configured.")
        return False
    api_url = f"https://api.github.com/repos/{GITHUB_USERNAME}/{GITHUB_REPO}/contents/{path}"
    headers = {"Authorization": f"token {GITHUB_PAT}", "Accept": "application/vnd.github.v3+json"}
    # check if exists
    r = requests.get(api_url, headers=headers, timeout=GITHUB_TIMEOUT)
    payload = {"message": commit_msg, "content": base64.b64encode(content_str.encode("utf-8")).decode("utf-8"), "branch": GITHUB_BRANCH}
    if r.status_code == 200:
        sha = r.json().get("sha")
        payload["sha"] = sha
    resp = requests.put(api_url, headers=headers, json=payload, timeout=GITHUB_TIMEOUT)
    if resp.status_code in (200,201):
        logger.info("Uploaded %s OK", path)
        return True
    else:
        logger.error("GitHub upload failed %s: %s %s", path, resp.status_code, resp.text[:200])
        return False

# ------------------------------
# Rate limiting and caching (Deta Base helpers)
# ------------------------------
def rate_limit_check(user_id: int) -> bool:
    """
    Persistent hourly limit using Deta Base.
    Key = f"user_{user}_{YYYYMMDDHH}"
    """
    if not rate_db:
        # fallback in-memory naive
        return True
    key = datetime.utcnow().strftime("%Y%m%d%H")
    rec_key = f"user_{user_id}_{key}"
    try:
        rec = rate_db.get(rec_key)
        if rec:
            cnt = rec.get("count",0)
            if cnt >= RATE_LIMIT_PER_HOUR:
                return False
            rec["count"] = cnt+1
            rate_db.put(rec, rec_key)
            return True
        else:
            rate_db.put({"count":1, "created": datetime.utcnow().isoformat()}, rec_key)
            return True
    except Exception as e:
        logger.exception("Rate DB error: %s", e)
        return True  # Fail-open for UX; adjust if you want fail-closed

def cache_lookup(file_sha: str) -> Optional[Dict[str, Any]]:
    """Return cached summary metadata if exists."""
    if not summaries_db:
        return None
    try:
        rec = summaries_db.get(file_sha)
        return rec
    except Exception as e:
        logger.exception("Cache lookup error: %s", e)
        return None

def cache_store(file_sha: str, meta: Dict[str,Any]):
    if not summaries_db:
        return
    try:
        summaries_db.put(meta, file_sha)
    except Exception as e:
        logger.exception("Cache store error: %s", e)

# ------------------------------
# Page rendering helpers
# ------------------------------
def render_summary_page(title: str, summary_html: str, key_points: List[str], quiz_path: str, monetag: str) -> str:
    t = Template(SUMMARY_TEMPLATE)
    return t.render(title=title, summary_html=summary_html, key_points=key_points, quiz_url=f"{PAGE_BASE}/{quiz_path}", monetag_code=monetag, ts=datetime.utcnow().isoformat())

def render_quiz_page(title: str, mcqs: List[Dict[str,Any]], monetag: str) -> str:
    answers = [q.get("answer","") for q in mcqs]
    t = Template(QUIZ_TEMPLATE)
    return t.render(title=title, mcqs=mcqs, monetag_code=monetag, answers_json=json.dumps(answers))

# ------------------------------
# Telegram handlers
# ------------------------------
async def start_cmd(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text("📚 PDF Study Bot (Groq). Send a PDF (as file) and I'll generate a summary + MCQ quiz (medium→hard).")

async def handle_pdf(update: Update, context: ContextTypes.DEFAULT_TYPE):
    msg = update.message
    user = msg.from_user
    user_id = user.id if user else None

    # rate limit
    if user_id and not rate_limit_check(user_id):
        await msg.reply_text("🚫 Rate limit reached. Try again in an hour.")
        return

    processing = await msg.reply_text("📥 Downloading PDF...")
    try:
        if not msg.document:
            await processing.edit_text("❌ Please send a PDF document file (not image).")
            return
        f = await msg.document.get_file()
        data = await f.download_as_bytearray()
        b = bytes(data)
        file_sha = sha256_bytes(b)

        # check cache
        cached = cache_lookup(file_sha)
        if cached:
            await processing.edit_text("♻️ Found cached result — returning existing pages...")
            summary_url = cached.get("summary_url")
            quiz_url = cached.get("quiz_url")
            await msg.reply_text(f"✅ Summary: {summary_url}\n📝 Quiz: {quiz_url}", disable_web_page_preview=False)
            return

        await processing.edit_text("🔍 Extracting text (this may take a few seconds)...")
        text = extract_text_from_pdf_bytes(b, page_limit=PAGE_LIMIT)
        if not text.strip():
            await processing.edit_text("❌ No extractable text found (maybe scanned pages). Consider OCR first.")
            return

        await processing.edit_text("🤖 Generating summary & MCQs with Groq (parallelizing calls)... This is fast.")
        # call generator
        gen_result = await generate_summary_and_mcqs(text)

        summary = gen_result.get("summary","")
        key_points = gen_result.get("key_points",[])[:8]
        mcqs = gen_result.get("mcqs",[])[:MAX_MCQS]

        # HTML pages
        shortid = file_sha[:8]
        summary_html = render_summary_page(msg.document.file_name or f"PDF_{shortid}", summary.replace("\n","<br/>"), key_points, f"quiz_{shortid}.html", MONETAG_CODE)
        quiz_html = render_quiz_page(msg.document.file_name or f"PDF_{shortid}", mcqs, MONETAG_CODE)

        await processing.edit_text("🌐 Publishing pages to GitHub Pages...")
        ok1 = github_api_put_file(f"summaries/summary_{shortid}.html", summary_html, commit_msg=f"Add summary {shortid}")
        ok2 = github_api_put_file(f"quiz/quiz_{shortid}.html", quiz_html, commit_msg=f"Add quiz {shortid}")

        if not (ok1 and ok2):
            await processing.edit_text("⚠️ Publishing failed. Returning summary in chat instead.")
            await msg.reply_text(summary[:3500] or "Summary generation failed.")
            return

        summary_url = f"{PAGE_BASE}/summaries/summary_{shortid}.html"
        quiz_url = f"{PAGE_BASE}/quiz/quiz_{shortid}.html"

        # store in cache
        cache_store(file_sha, {"summary_url": summary_url, "quiz_url": quiz_url, "created": datetime.utcnow().isoformat()})

        await processing.edit_text(f"✅ Ready!\n\nSummary: {summary_url}\nQuiz: {quiz_url}", disable_web_page_preview=False)

    except Exception as e:
        logger.exception("Error in handle_pdf: %s", e)
        try:
            await processing.edit_text("❌ Error processing PDF. Try a smaller file or contact admin.")
        except:
            pass

async def error_handler(update: Optional[Update], context: ContextTypes.DEFAULT_TYPE):
    logger.error("Update %s caused error %s", update, context.error)

# ------------------------------
# Run bot
# ------------------------------
def main():
    if not TELEGRAM_BOT_TOKEN:
        logger.error("TELEGRAM_BOT_TOKEN missing. Export env var and retry.")
        return
    app = Application.builder().token(TELEGRAM_BOT_TOKEN).build()
    app.add_handler(CommandHandler("start", start_cmd))
    app.add_handler(MessageHandler(filters.Document.PDF, handle_pdf))
    app.add_error_handler(error_handler)
    logger.info("Starting bot (polling)...")
    app.run_polling()

if __name__ == "__main__":
    main()
